In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("Exam1_Gradescope.ipynb")

## Exam 1

**Northeastern University Honor Code**\
On my honor, I pledge to uphold the values of honesty, integrity, and respect that are expected of me as a Northeastern student.

**Signature: Jacob Kulik**

#### Import the Necessary Libraries

In [2]:
import numpy as np

### PART 1

---

#### 1. Select the ticker for Adobe ('ADBE') from the below-defined list and store it in a variable called **ans1**

_Points:_ 7.5

In [3]:
lst = [['CSCO'],[['INTC','FB'],'IBM','FB'],['WMT',['ADBE','XOM']]]

In [4]:
ans = lst[-1][-1][0]
ans

'ADBE'

---

#### 2. Create a variable called **ans2** to store the word 'FinTech', selected from the below-defined string using the `split()` function.

_Points:_ 4.5

In [5]:
string ='Financial Data Analytics with Python is awesome!#Northeastern#FinTech'

In [6]:
ans2 = string.split('#')[-1]
ans2

'FinTech'

---

#### 3. Create a new list labeled **ans3** that contains only the tickers that start with the letter "B" and have an odd number of characters from the below-defined list of tickers.

_Points:_ 7.5

In [7]:
tickers = ['AAPL', 'COST', 'AMD', 'ADBE','EBAY','TSLA', 'AMZN', 'FB', 'BA', 'CSCO', 'INTC', 'EA','ADI','BBY']

In [8]:
ans3 = [ticker for ticker in tickers if ticker[0].lower() == 'b' and len(ticker) % 2 != 0]
ans3

['BBY']

---

#### 4. Define a function named **sm_even(A,B)** that calculates the sum of all even integers in the interval [A,B].

_Points:_ 7.5

In [9]:
def sm_even(A,B):
    sm = 0
    for num in range(A, B+1):
        if num % 2 == 0:
            sm += num
    return sm

In [10]:
sm_even(2,7)

12

---

#### 5. Define a function named **bd_new(c_rate,ytm,years)** that computes the price of a bond that pays coupon three times a year. Use the annual coupon rate (input as a percentage), the annual yield to maturity (YTM) (input as a percentage) and the number of years to maturity as parameters.

$Bond price = \sum_{i=1}^{N}\frac{Coupon}{(1+YTM)^i}+\frac{Face Value_N}{(1+YTM)^N}$

_Points:_ 7.5

In [11]:
def bd_new(c_rate,ytm,years):
    tri_annual_rate = c_rate / (3 * 100)
    tri_annual_ytm = ytm / (3 * 100)
    tri_payment = 1000 * tri_annual_rate
    
    prc = 0
    # pv of coupons
    for i in range(1, 3 * years + 1):
        prc += tri_payment / ((1 + tri_annual_ytm) ** i)
        
    # pv of the par value at maturity
    prc += 1000 / ((1 + tri_annual_ytm) ** (years * 3))
    return prc

In [12]:
bd_new(3, 5, 30)

690.3623204654907

---

#### 6. Define a function named **pvann_late(T,PMT,rate,N)** that calculates the present value of a level stream of payments, with the first payment made T years from now. Use T, the annual payment, the annual discount rate (input as a percentage) and N (the number of payments) as parameters.

$PV Annuity Late = \sum_{i=T}^{N+T-1}\frac{PMT}{(1+rate)^i}$

_Points:_ 7.5

In [13]:
def pvann_late(T,PMT,rate,N):
    pv = 0
    rate = rate / 100
    
    for i in range(T, N + T):
        pv += PMT / ((1 + rate) ** i)
    return pv

In [14]:
pvann_late(5,100,5,10)

635.2690435927261

### PART 2

#### Use your NEU ID # in the code below. There will be a significant point discount for failing to do so.

In [15]:
params = {'NEU_ID': 2113579
          #Replace 100 with your actual NEU ID#
         }

In [16]:
np.random.seed(params['NEU_ID'])
arr = np.random.randint(-19,19,(9,9))
print('This is the initial array you will be using in Part2. It is stored in a \
variable called arr:',end='\n\n')
print(arr)

This is the initial array you will be using in Part2. It is stored in a variable called arr:

[[-15  -8  -4   2   8  13 -18   4  -7]
 [  9  -2  -3  14 -13 -16   1   4  -1]
 [ 12   6  -7  13  -3   4  16 -16   0]
 [-15 -10  -5  -9  13   4   1  18 -18]
 [ 17   1   6  -9  11 -18   7 -19 -15]
 [-10   5  -1 -11  12  11   8  16   7]
 [ 11   2  -3  16   4   3  -2  17  15]
 [  3  14   5  -4 -18  16 -11  11  -1]
 [ -1  14   0 -13  11   8   2  -4  -8]]


---

#### 7. Create a variable called **ans7** to store the index for the lowest value in the seventh row in the above defined array **arr**.

_Points:_ 7.5

In [17]:
ans7 = np.argmin(arr[6, :])
ans7

2

---

#### 8. Create a variable called **ans8** to store the mean of all the elements in the above defined array *arr* that are in the interval (-3,10]

_Points:_ 7.5

In [18]:
ans8 = arr[(arr > -3) & (arr <= 10)].mean()
ans8

3.096774193548387

---

#### 9. Create a new array named **ans9** to store the even numbers found in the last three columns in the above defined array **arr**.

_Points:_ 7.5

In [19]:
last3 = arr[:, -3:]
ans9 = last3[last3 % 2 == 0]
ans9

array([-18,   4,   4,  16, -16,   0,  18, -18,   8,  16,  -2,   2,  -4,
        -8])

---

#### 10. Create a new array named **ans10** to store the mean of the elements in each column in the array at the intersection (slice) of the the second through the fourth rows and first three columns from the above-defined array **arr**

_Points:_ 7.5

In [20]:
ans10 = np.mean(arr[1:4, :3], axis = 0)
ans10

array([ 2., -2., -5.])

---

#### 11. Create a new array called **ans11** to store the largest and lowest values on the main diagonal in the above defined array **arr**.

_Points:_ 7.5

In [21]:
diag = np.diag(arr)
ans11 = np.array([diag.max(), diag.min()])
ans11

array([ 11, -15])

---

#### 12. Use a for loop to count how many elements on the antidiagonal in the above-defined array **arr** are in the interval [-12,1). Store their number in a variable called **ans12**.

_Points:_ 4.5

In [22]:
#flipping array
anti_diag = np.diag(np.fliplr(arr))

ans12 = 0
for val in anti_diag:
    if val >= -12 and val < 1:
        ans12 += 1
ans12

4

---

#### 13. Use a *for loop* to calculate the sum of all the elements that are in the interval (-16,5] in the first five columns of the above-defined array **arr**. Store the sum in a variable labeled **ans13**. 

_Points:_ 4.5

In [23]:
ans13 = 0
for row in arr[:, :5]:
    for val in row:
        if val > -16 and val <= 5:
            ans13 += val

ans13

-124

---

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [24]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False, run_tests=True)

Running your submission against local test cases...



Your submission received the following results when run against available test cases:


