In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("HW1_Gradescope.ipynb")

# Homework 1

## Instructions

1. Do not move or rename the included files. If you move or rename files or folders, the local and Gradescope autograders will not work.
1. Refer to files and variables exactly as they appear. Python is case-sensitive, so `df` and `DF` are different variables.
1. After you answer a question, you may run its public tests.
1. After you answer every question:
    1. Restart your kernel
    1. Run up to the last cell
    1. Save your notebook
    1. Run the last cell, which creates the .zip file for Gradescope in the same folder as this notebook
    1. Upload the .zip file to Gradescope
    1. Make sure your local autograder results match your Gradescope autograder results
1. ***The public tests ensure your answers are formatted correctly but do not ensure your answers are correct.***
1. Gradescope runs hidden tests in addition to the public tests but does not reveal public test results until after the due date. Your grade will be "~/100" until after the due date.

## Packages

In [2]:
import numpy as np

## Questions

---

<!-- BEGIN QUESTION -->

#### 1. Use a ***for loop*** and an ***if statement*** to print out all the three letter words that end with 'e' in the following string.

_Points:_ 10

In [3]:
string = 'You are welcome to attend the opening of the new hockey season at TD Garden.'

In [4]:
for str in string.split(' '):
    if str[-1].lower() == 'e' and len(str) == 3:
        print(str)

are
the
the


<!-- END QUESTION -->

---

#### 2. Define a function labeled **counter** that counts the number of words in a string. A word is defined as a string with at least two characters.

_Points:_ 10

In [5]:
def counter(str):
    ''' counts the number of words in a str
    parameters: str - string
    returns: number of words in a string
    '''
    split = str.split(' ')
    words = []
    for word in split:
        if len(word) >= 2:
            words.append(word)
        
    return len(words)

In [6]:
grader.check("q2")

q2 results: All test cases passed!
q2 - 1 message: counter is properly defined (+5 pts)
q2 - 2 message: the counter function provides the right answer (+5 pts)

---

<!-- BEGIN QUESTION -->

#### 3. Use the below-defined list and a lambda function to create a new list labeled **new_lst** of strings such that each string's characters must be in lower case and sorted in reverse order 

_Points:_ 10

In [7]:
tickers3 = ["IBM", "AAPL", "FB", "MCD", "WMT", "GOOGL"]

In [8]:
# lowering, then reversing
new_ls = list(map(lambda ticker: ticker[::-1].lower(), tickers3))
new_ls

['mbi', 'lpaa', 'bf', 'dcm', 'tmw', 'lgoog']

<!-- END QUESTION -->

---

<!-- BEGIN QUESTION -->

#### 4. Use the following list and the *filter ()* function to create another list, such that each element's length is a multiple of three.

_Points:_ 10

In [9]:
tickers4 = ["IBM", "AAPL", "FB", "MCD", "GOOGL", "M", ]

In [10]:
# finding length mod 3 tickers
new_ls = list(filter(lambda ticker: len(ticker) % 3 == 0, tickers4))
new_ls

['IBM', 'MCD']

<!-- END QUESTION -->

---

#### 5. Define a function labeled **fv_ann_due** that calculates the future value of an annuity due. Use the payment, the annual discount rate and the number of payments as parameters.

$FV Annuity Due = \sum_{i=0}^{N-1}PMT*{(1+rate)^i}$

_Points:_ 10

In [11]:
def fv_ann_due(payment, rate, num_p):
    ''' calculating the future value of an annuity due
    parameters - payment, annual discount rate, num_p -> ints
    returns - the float val, rounded to 10 decimals
    '''
    summation = 0
    # going through iteration
    for i in range(num_p):
        summation += payment * (1 + rate / 100) ** (i + 1)
    return round(summation, 10)

In [12]:
grader.check("q5")

q5 results: All test cases passed!
q5 - 1 message: fv_ann_due is properly defined (+5 pts)
q5 - 2 message: the fv_ann_due function provides the right answer (+5 pts)

---

#### 6. Set the random seed at 1000, and generate a 6x6 array of random integers in the interval [10,1000]. Store the array in a variable named *arr6*.

_Points:_ 10

In [13]:
import numpy as np
np.random.seed(1000)
arr6 = np.random.randint(10, 1001, (6, 6))

In [14]:
grader.check("q6")

q6 results: All test cases passed!
q6 - 1 message: arr6 has the correct shape (+5 pts)
q6 - 2 message: arr6 has the correct values (+5 pts)

---

#### 7. Create a variable labeled *arr7* to store the mean of the elements in each column in the array at the intersection (slice) of the first two rows and the last three columns from the above-defined array *arr6*.

_Points:_ 10

In [15]:
arr7 = np.mean(arr6[:2, -3:], axis = 0)

In [16]:
grader.check("q7")

q7 results: All test cases passed!
q7 - 1 message: arr7 has the correct size (+5 pts)
q7 - 2 message: weights has the correct values (+5 pts)

---

#### 8. Create a variable labeled *arr8* to store the sum of all the elements that are in the interval [95,700] in the first four rows of the above-defined array *arr6* 

_Points:_ 10

In [17]:
arr8 = np.sum(np.where((arr6[:4] >= 95) & (arr6[:4] <= 700), arr6[:4], 0))

In [18]:
grader.check("q8")

q8 results: All test cases passed!
q8 - 1 message: arr8 has the correct value (+10 pts)

---

#### 9. Use a *for loop* to calculate the sum of all the elements that are in the interval [75,900] in the last three rows of the above-defined array *arr6*. Store the sum in a variable labeled *sum1*.  

_Points:_ 7

In [19]:
sum1 = 0
for row in arr6[-3:]:
    #checking the given rows for the certain items, then adding them up
    for item in row:
        if 75 <= item and item <= 900:
            sum1 += item
print(sum1)

6890


In [20]:
grader.check("q9")

q9 results: All test cases passed!
q9 - 1 message: sum1 has the correct value (+7 pts)

---

<!-- BEGIN QUESTION -->

#### 10. Use a *for loop* to print the elements on the antidiagonal in the above defined array *arr6*. See the following link for additional details: https://en.wikipedia.org/wiki/Main_diagonal

_Points:_ 10

In [21]:
antidiag = np.diag(arr6, k=-1)
# going down the antidiag
for elem in antidiag:
    print(elem)
print(arr6)

358
883
308
243
215
[[445 609  81 714 261 360]
 [358 779 455 650 867 567]
 [562 883 358 229 302 710]
 [503 505 308 324 947 238]
 [670 508 296 243 354 892]
 [424 934 424 254 215 732]]


<!-- END QUESTION -->

---

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [22]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False, run_tests=True)

Running your submission against local test cases...



Your submission received the following results when run against available test cases:

    q2 results: All test cases passed!
    q2 - 1 message: counter is properly defined (+5 pts)
    q2 - 2 message: the counter function provides the right answer (+5 pts)

    q5 results: All test cases passed!
    q5 - 1 message: fv_ann_due is properly defined (+5 pts)
    q5 - 2 message: the fv_ann_due function provides the right answer (+5 pts)

    q6 results: All test cases passed!
    q6 - 1 message: arr6 has the correct shape (+5 pts)
    q6 - 2 message: arr6 has the correct values (+5 pts)

    q7 results: All test cases passed!
    q7 - 1 message: arr7 has the correct size (+5 pts)
    q7 - 2 message: weights has the correct values (+5 pts)

    q8 results: All test cases passed!
    q8 - 1 message: arr8 has the correct value (+10 pts)

    q9 results: All test cases passed!
    q9 - 1 message: sum1 has the correct value (+7 pts)
