### FINA 4380 with Marius Popescu

### Matrix Algebra Basics

In [12]:
import numpy as np
import pandas as pd

In [13]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [14]:
np.random.seed(100)
matrix = pd.DataFrame(np.random.randint(0,5,(4,3)),
                      columns = ['Stock1', 'Stock2', 'Stock3'],
                     index=['A','B','C','D'])
matrix

Stock1  Stock2  Stock3
A       0       0       3
B       0       2       4
C       2       2       2
D       2       1       0

In [15]:
product1 = np.dot(matrix,ones)

In [16]:
product1

array([3., 6., 6., 3.])

In [17]:
product1_df = pd.DataFrame(np.dot(matrix,ones),
                           columns=['Product'],
                           index=matrix.index)
product1_df

Product
A      3.0
B      6.0
C      6.0
D      3.0

In [18]:
product2 = np.dot(ones,matrix)

ValueError: shapes (3,) and (4,3) not aligned: 3 (dim 0) != 4 (dim 0)

In [19]:
matrix.T

A  B  C  D
Stock1  0  0  2  2
Stock2  0  2  2  1
Stock3  3  4  2  0

In [20]:
matrix.transpose()

A  B  C  D
Stock1  0  0  2  2
Stock2  0  2  2  1
Stock3  3  4  2  0

In [21]:
product2 = np.dot(ones,matrix.T)
product2

array([3., 6., 6., 3.])

In [22]:
product2_df = pd.DataFrame(np.dot(ones,matrix.T),
                           columns=['Product'],
                           index=matrix.index)
product2_df

Product
A      3.0
B      6.0
C      6.0
D      3.0