### FINA 4380 with Marius Popescu

### NumPy - Exercises Solutions

#### Import NumPy

In [1]:
import numpy as np

#### 1. Set the random seed at 1000, generate an array of 25 random integers in the interval [0, 50] and reshape it into a 5x5 matrix. Store the array in a variable named *arr*. Print the resulting array.

In [3]:
np.random.seed(1000)
arr = np.random.randint(0,51,(5,5))
arr

array([[23,  7,  0, 30, 28],
       [ 1,  0, 25, 45, 40],
       [41, 28, 27, 36, 45],
       [47, 42, 41, 36, 20],
       [50, 30, 41, 24, 50]])

### We will use the above-defined array for all the following questions

#### 2. Select the element at the intersection of the second row and the third column

In [4]:
arr[1,2]

25

#### 3. Slice the first two rows and all columns

In [6]:
arr[:2,:]

array([[23,  7,  0, 30, 28],
       [ 1,  0, 25, 45, 40]])

#### 4. Slice the last three rows, but only the third column 

In [7]:
arr[-3:,2]

array([27, 41, 41])

#### 5. Slice all rows, but only the second column

In [8]:
arr[:,1]

array([ 7,  0, 28, 42, 30])

#### 6. Slice the first two rows and the last two columns

In [9]:
arr[:2,-2:]

array([[30, 28],
       [45, 40]])

#### 7. Calculate the mean of the elements in each row

In [10]:
arr.mean(axis=1)

array([17.6, 22.2, 35.4, 37.2, 39. ])

#### 8. Calculate the sum of the elements in each column

In [11]:
arr.sum(axis=0)

array([162, 107, 134, 171, 183])

In [12]:
arr[:,2].sum(axis=0)

134

#### 9. What is the index for the highest value in the fourth row

In [15]:
arr[3, :].argmax()

0

In [16]:
arr.argmax(axis=1)

array([3, 3, 4, 0, 0], dtype=int64)

#### 10. What is the lowest value in the array at the intersection (slice) of the last two rows and the first two columns

In [17]:
arr[-2:,:2].min()

30

#### 11. Return all the elements that are higher than the median value for the entire array

In [18]:
arr[arr>np.median(arr)]

array([45, 40, 41, 36, 45, 47, 42, 41, 36, 50, 41, 50])

#### 12. Calculate the sum of all the elements that are higher than 15

In [19]:
np.sum(arr[arr>15])

749

#### 13. Use a *for loop* to count the number of elements that are higher than 15

#### 14. Print all the elements that are odd

In [21]:
[print(val) for val in arr[arr%2 == 1]]

23
7
1
25
45
41
27
45
47
41
41


[None, None, None, None, None, None, None, None, None, None, None]

#### 15. Use a *for loop* to print the elements on the main diagonal

In [25]:
for i in range(len(arr)):
    print(arr[i,i])

23
0
27
36
50


#### 16. Use a for loop to count how many elements on the main diagonal are positive

In [ ]:
counter = 0
[counter+=1 for ]

#### 17. Use a for loop to count how many elements on the main diagonal have missing values

#### 18. Define a function to compute the mean of the elements on the main diagonal of a two-dimensional array. Apply it for the above-defined array *arr*. *Hint: Explore the array_name.diagonal() method*