### FINA 4380 with Marius Popescu

## NumPy - Part II

In [1]:
import numpy as np

In [2]:
# Generate a 3x4 matrix of random integers from the interval [0,20]
np.random.seed(1000)
arr = np.random.randint(0,21,(3,4))
print(arr)

[[19  7  0  1]
 [ 0 13  8  9]
 [ 4 13 15 10]]


### NumPy Array Methods

#### `array_name.transpose()` can also be used to transpose an array

In [3]:
arr.transpose()

array([[19,  0,  4],
       [ 7, 13, 13],
       [ 0,  8, 15],
       [ 1,  9, 10]])

#### `array_name.reshape()` returns an array containing the same data with a new shape
Note that for this to work, the size of the initial array must match the size of the reshaped array.

In [4]:
arr.reshape(1,12)

array([[19,  7,  0,  1,  0, 13,  8,  9,  4, 13, 15, 10]])

In [5]:
arr.reshape(12)

array([19,  7,  0,  1,  0, 13,  8,  9,  4, 13, 15, 10])

#### `array_name.flatten()` converts a two-dimensional array into a one-dimensional

In [6]:
arr.flatten()

array([19,  7,  0,  1,  0, 13,  8,  9,  4, 13, 15, 10])

### Mathematical and Statistical Methods
These methods are used to find the **sum**, **mean**, **standard deviation**, **maximum**, **minimum**, and indices of the maximum (**argmax**) and minimum (**argmin**), respectively.

#### * Statistics for the entire array

In [34]:
# Sum
arr.sum()

99

In [42]:
# Mean
arr.mean()

8.25

In [36]:
# Standard Deviation
arr.std()

5.903741751352837

In [37]:
# Maximum
arr.max()

19

In [38]:
# Index of the Maximum
arr.argmax()

0

In [39]:
# Minimum
arr.min()

0

In [43]:
# Index of the Minimum
arr.argmin()

2

#### * Statistics for each row (across columns)

In [44]:
# Sum
arr.sum(axis = 1)

array([27, 30, 42])

In [29]:
# Maximum
arr3.max(axis = 1)

array([3, 6, 9])

In [52]:
# Index of Maximum
arr.argmax(axis = 1)

array([0, 1, 2])

#### * Statistics for each column (across rows)

In [7]:
# Mean
arr.mean(axis = 0)

array([ 7.66666667, 11.        ,  7.66666667,  6.66666667])

In [49]:
# Minimum
arr.min(axis = 0)

array([0, 7, 0, 1])

In [47]:
# Index of the Minimum
arr.argmin(axis = 0)

array([1, 0, 0, 0])

### NumPy Universal Functions
A universal function, or *ufunc*, is a function that performs a mathematical operation across the array.

In [53]:
# Sum
np.sum(arr)

99

In [54]:
# Mean
np.mean(arr)

8.25

In [55]:
# Median
np.median(arr)

8.5

In [56]:
# Maximum
np.max(arr)

19

In [57]:
# Minimum
np.min(arr)

0

In [40]:
# Square
np.square(arr3)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [39]:
# Square root
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])